name: mobile_client
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_simple_dependency_injection: ^2.0.0
  easy_web_view: ^1.6.0
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  dots_indicator: ^2.1.0
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: SF UI Display
      fonts:
        - asset: fonts/SFUIDisplay-Black.ttf
          weight: 900
        - asset: fonts/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: fonts/SFUIDisplay-Heavy.ttf
          weight: 600
        - asset: fonts/SFUIDisplay-Light.ttf
          weight: 300
        - asset: fonts/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: fonts/SFUIDisplay-Regular.ttf
          weight: 400
        - asset: fonts/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: fonts/SFUIDisplay-Thin.ttf
          weight: 200
        - asset: fonts/SFUIDisplay-Ultralight.ttf
          weight: 100

flutter_intl:
  main_locale: ru
  enabled: true
